apiVersion: v1
kind: Service
metadata:
  name: appservice
spec:
  selector:
    app: next-result
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000
  type: NodePort
